const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94764703165"
const SESSION_ID = "PRABATH-MD~5mUSXBqA#HgFeOwJFaCDgsG7XWgPMX9rNDO_G1aAVbgYuYQ80nNs"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
